src/Client/Models/Game.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Client.Models
{
    public partial class Game
    {
        public Game()
        {
            MapOfGames = new List<MapOfGame>();
        }

        public int GameId { get; set; }
        public DateTime GameDate { get; set; }
        public int EventId { get; set; }
        public int TeamAId { get; set; }
        public int TeamBId { get; set; }
        public int? TeamWinnerId { get; set; }

        public Event Event { get; set; }
        public Team TeamA { get; set; }
        public Team TeamB { get; set; }
        public Team? TeamWinner { get; set; }
        public virtual List<MapOfGame> MapOfGames { get; set; }
        public virtual List<StatPlayerOnGame> StatPlayerOnGame { get; set; }
    }
}

src/Client/Models/MapOfGame.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Client.Models
{
    public partial class MapOfGame
    {
        public int MapOfGameId { get; set; }
        public int? TeamAresult { get; set; }
        public int? TeamBresult { get; set; }
        public int MapaId { get; set; }
        public int GameId { get; set; }

        public virtual Game Game { get; set; }
        public virtual Map Mapa { get; set; }
    }
}

src/Client/Controllers/GamesController.cs
using Client.Models;
using Client.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class GamesController : Controller
    {
        GamesRepository contextGames = null;
        EventsRepository contextEvents = null;
        StatPlayerOnGameRepository contextStatPlayerOnGame = null;
        MapOfGameRepository contextMapOfGame = null;

        public GamesController()
        {
            contextGames = new GamesRepository();
            contextEvents = new EventsRepository();
            contextStatPlayerOnGame = new StatPlayerOnGameRepository();
            contextMapOfGame = new MapOfGameRepository();
        }


        /// <summary>
        /// Pagina inicial dos jogos
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <returns>Retorna a view</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Index(int? id)
        {
            try
            {
                ViewBag.Event = await contextEvents.GetEventById(id);
                ViewBag.Games = await contextGames.GetGameByEventId(id);
            }
            catch (Exception e)
            {
                View("Error", new Error() { Title = "Listagem de jogos", Message = e.Message });
            }

            if (ViewBag.Event == null || ViewBag.Games == null)
            {
                return NotFound();
            }
            //
            return View();
        }


        /// <summary>
        /// Pagina para criar novo jogo
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <returns>Retorna a view</returns>
        [Authorize(Roles = "Admin,User")]
        public IActionResult Create(int? id)
        {
            //
            var ev = contextEvents.GetEventById(id);
            List<Team> teamA = ev.Result.Teams.AsEnumerable().ToList();
            List<Team> teamB = ev.Result.Teams.AsEnumerable().ToList();
            teamA.RemoveAt(1);
            teamB.RemoveAt(0);
            ViewBag.Event = ev.Result;
            ViewBag.TeamsA = new SelectList(teamA, nameof(Team.TeamId), nameof(Team.TeamName));
            ViewBag.TeamsB = new SelectList(teamB, nameof(Team.TeamId), nameof(Team.TeamName));
            
            return View();
        }


        /// <summary>
        /// Adiciona novo jogo ao evento
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <param name="game">objeto do novo jogo</param>
        /// <returns>Retorna a view</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Create(int? id, [Bind("EventId,GameId,GameDate,TeamAId,TeamBId,TeamWinnerId")] Game @game)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    game.EventId = (int)id;
                    Game gm = await contextGames.AddNewGame(HttpContext, @game);
                    if(gm != null)
                    {
                        foreach (var item in gm.TeamA.Players)
                        {
                            StatPlayerOnGame stg = new StatPlayerOnGame() { Player = item, PlayerId = item.PlayerId, Adr = 0, Deaths = 0, Game = gm, GameId = gm.GameId, Kills = 0, Rating = 0, Team = gm.TeamA, TeamId = gm.TeamA.TeamId };
                            await contextStatPlayerOnGame.AddNewStatPlayerOnGame(HttpContext, stg);
                        }

                        foreach (var item in gm.TeamB.Players)
                        {
                            StatPlayerOnGame stg = new StatPlayerOnGame() { Player = item, PlayerId = item.PlayerId, Adr = 0, Deaths = 0, Rating = 0, Game = gm, GameId = gm.GameId, Kills = 0, Team = gm.TeamB, TeamId = gm.TeamB.TeamId };
                            await contextStatPlayerOnGame.AddNewStatPlayerOnGame(HttpContext, stg);
                        }
                    }

                    return RedirectToAction("Index", new { id = game.EventId });
                }
            }
            catch (Exception e)
            {
                View("Error", new Error() { Title = "Novo Jogo", Message = e.Message });
            }

            return View(@game);
        }


        /// <summary>
        /// Pagina para a gestão dos mapas do jogo
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <returns>Retorna a view</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Maps(int? id)
        {
            return null;
        }


        /// <summary>
        /// Pagina para a gestão das estatisticas
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <returns>Retorna a view</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Stats(int? id)
        {
            Game gm;
            try
            {
                if ((gm = await contextGames.GetGameById(id)) != null)
                {
                    ViewBag.Game = gm;
                    return View();
                }
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Estatisticas", Message = e.Message });
            }
            

            return new EmptyResult();
        }


        /// <summary>
        /// Adiciona novo mapa ao jogo
        /// </summary>
        /// <param name="mapOfGame">objeto com o mapa</param>
        /// <returns>Retorna o resultado</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> AddMapOfGame([Bind("MapaId, GameId, TeamAresult, TeamBresult")] MapOfGame mapOfGame)
        {
            MapOfGame map = null;
            try
            {
                if (mapOfGame != null)
                {
                    if((map = await contextMapOfGame.AddNewMapOfGame(HttpContext, mapOfGame)) != null)
                    {
                        return RedirectToAction("MapOfGame", new { id = mapOfGame.GameId });
                    }
                }
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Mapas jogados", Message = e.Message });
            }
            return View("~/Views/Home/Events.cshtml");
        }


        /// <summary>
        /// Remove mapa do jogo
        /// </summary>
        /// <param name="id">id do jogo</param>
        /// <param name="idMapOfGame">id do mapa</param>
        /// <returns>Retorna o resultado</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> RemoveMapOfGame(int? id, int? idMapOfGame)
        {
            try
            {
                if(id != null && idMapOfGame != null)
                    if(await contextMapOfGame.DeleteMapOfGame(HttpContext, idMapOfGame))
                        return RedirectToAction("MapOfGame", new { id = id });
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Remover mapa jogado", Message = e.Message });
            }
            return View("~/Views/Home/Events.cshtml");
        }


        /// <summary>
        /// Abre a gestão de mapas do jogo
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <returns>Retorna a view</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> MapOfGame(int? id)
        {
            var mapOfGame = await contextMapOfGame.GetMapOfGameByGameId(id);
            var maps = await new MapsRepository().GetAllMaps(HttpContext);
            var mapsOutOfGame = maps.Where(l2 => !mapOfGame.Any(l1 => l1.MapaId == l2.MapId)).ToList();
            ViewBag.GameId = id;
            ViewBag.EventId = (await contextGames.GetGameById(id)).EventId;
            ViewBag.Maps = new SelectList(mapsOutOfGame, nameof(Map.MapId), nameof(Map.Description));
            ViewBag.MapsOfGame = mapOfGame;

            return View();
        }


        /// <summary>
        /// Edita as estatisticas do jogo
        /// </summary>
        /// <param name="id">id do jogo</param>
        /// <param name="stat">objeto das estatisticas do jogo</param>
        /// <returns>Retorna true/false</returns>
        [HttpPost]
        [Authorize(Roles = "Admin,User")]
        public async Task<bool> EditStat(int? id, [Bind("StatPlayerOnGameId,GameId,TeamId,PlayerId,Kills,Deaths,Adr,Rating")] StatPlayerOnGame stat)
        {
            try
            {
                if (stat != null && stat.StatPlayerOnGameId != null)
                {
                    return await contextStatPlayerOnGame.EditStatPlayerOnGame(HttpContext, stat, stat.StatPlayerOnGameId);
                }
                return false;               
            }
            catch (Exception)
            {
                return false;
            }
        }


        /// <summary>
        /// Devolve as equipas que podem ser escolhidas
        /// </summary>
        /// <param name="id">id do jogo</param>
        /// <param name="team">id da equipa ocupada</param>
        /// <returns>Retorna as equipas</returns>
        [HttpPost]
        [Authorize(Roles = "Admin,User")]
        public async Task<IEnumerable<object>> GetTeamsExcluded([Bind("id,team")]int? id, int? team)
        {
            try
            {
                if (id == null || team == null || team == 0)
                    return null;

                var auxTeams = contextEvents.GetEventById(id).Result.Teams;

src/Client/Views/Games/Create.cshtml
@model Client.Models.Game

@{
    ViewData["Title"] = "Create";
    int id = ViewBag.Event.EventId;
}

<h1>Criar novo jogo</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Games" asp-action="Create">
            <input type="hidden" asp-for="EventId" value="@id" />
            <div class="form-group">
                <label class="control-label">Data</label>
                <input asp-for="GameDate" class="form-control" />
                <span asp-validation-for="GameDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Equipa A</label>
                <select id="TeamA" asp-for="TeamAId" class="form-control" asp-items="@ViewBag.TeamsA"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Equipa B</label>
                <select id="TeamB" asp-for="TeamBId" class="form-control" asp-items="@ViewBag.TeamsB"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Equipa Vencedora</label>
                <select id="TeamWinner" asp-for="TeamWinnerId" class="form-control">
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar novo jogo" class="btn btn-success" />
                <a asp-action="Index" asp-route-id="@ViewBag.Event.EventId" class="btn btn-danger">Descartar Dados</a>
            </div>
        </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.js"></script>
<script>
    $(document).ready(function () {
        reset();
    });

    $('#TeamA').on("change", function () { TeamAChange(); reset(); });
    $('#TeamB').on("change", function () { TeamBChange(); reset(); });

    function reset() {
        $('#TeamWinner').text('');
        $('#TeamWinner').append('<option value="0">Sem Vencedor</option>');
        $('#TeamWinner').append(new Option($("#TeamA option:selected").text(), $("#TeamA option:selected").val()));
        $('#TeamWinner').append(new Option($("#TeamB option:selected").text(), $("#TeamB option:selected").val()));
    }

    function TeamAChange() {
        var teamB = $("#TeamB option:selected").val()
        $.post("/Games/GetTeamsExcluded",
            {
                id: @ViewBag.Event.EventId,
                team: $("#TeamA option:selected").val()
            },
            function (data, status) {
                if (data != null) {
                    $("#TeamB").text('');
                    for (var i = 0; i < data.length; i++) {
                        if (teamB == data[i].value)
                            $("#TeamB").append('<option value="' + data[i].value + '" selected>' + data[i].text + '</option>');
                        else
                            $("#TeamB").append('<option value="' + data[i].value + '">' + data[i].text + '</option>');
                    }
                }
            });
    }

    function TeamBChange() {

        var teamA = $("#TeamA option:selected").val()
        $.post("/Games/GetTeamsExcluded",
            {
                id: @ViewBag.Event.EventId,
                team: $("#TeamB option:selected").val()
            },
            function (data, status) {
                if (data != null) {
                    $("#TeamA").text('');
                    for (var i = 0; i < data.length; i++) {
                        if (teamA == data[i].value)
                            $("#TeamA").append('<option value="' + data[i].value + '" selected>' + data[i].text + '</option>');
                        else
                            $("#TeamA").append('<option value="' + data[i].value + '">' + data[i].text + '</option>');
                    }
                }
            });
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Client/Views/Games/Delete.cshtml
@model Client.Models.Game

@{
    ViewData["Title"] = "Eliminar Competição";
}

<h1>Eliminar Competição</h1>

<h3>Tem certeza que deseja eliminar esta competição?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Data
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GameDate)
        </dd>
        <dt class="col-sm-2">
            Team A
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TeamA.TeamName)
        </dd>
        <dt class="col-sm-2">
            Team B
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TeamB.TeamName)
        </dd>
        <dt class="col-sm-2">
            Team Vencedora
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TeamWinner.TeamName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GameId"/>
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        <a asp-action="Index" asp-route-id="EventId" class="btn btn-info">Voltar para a listagem</a>
    </form>
</div>

src/Client/Views/Games/Edit.cshtml
@model Client.Models.Game

@{
    ViewData["Title"] = "Editar Jogo";
    int id = ViewBag.Event.EventId;
}

<h1>Editar Jogo</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="EventId"/>
            <input type="hidden" asp-for="GameId"/>
            <div class="form-group">
                <label class="control-label">Data</label>
                <input asp-for="GameDate" class="form-control" />
                <span asp-validation-for="GameDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Equipa A</label>
                <input type="hidden" asp-for="TeamAId"/>
                <input id="TeamA" class="form-control" disabled  value="@Model.TeamA.TeamName"/>
            </div>
            <div class="form-group">
                <label class="control-label">Equipa B</label>
                <input type="hidden" asp-for="TeamBId" />
                <input id="TeamA" class="form-control" disabled value="@Model.TeamB.TeamName" />
            </div>
            <div class="form-group">
                <label class="control-label">Equipa Vencedora</label>
                <select id="TeamWinner" asp-for="TeamWinnerId"  class="form-control" asp-items="@ViewBag.TeamsWinner">
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar Jogo" class="btn btn-success"/>
                <a asp-action="Index" asp-route-id="@ViewBag.Event.EventId" class="btn btn-danger">Descartar Dados</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Client/Views/Games/Index.cshtml
@model Client.Models.Event

@{
    ViewData["Title"] = "Competições";
}


<hr />

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h5>Nome do Evento</h5>
            <p>@ViewBag.Event.EventName</p>
        </div>
        <div class="col-md-4">
            <h5>Data de Inicio</h5>
            <p>@ViewBag.Event.DateOfStart</p>
        </div>
        <div class="col-md-4">
            <h5>Data de Fim</h5>
            <p>@ViewBag.Event.DateOfEnd</p>
        </div>
    </div>
    <hr />
    <h1>Jogos</h1>
    <div class="row">
        <div class="col-md-12">
            <p>
                <a asp-action="Create" asp-route-id="@ViewBag.Event.EventId" class="btn btn-success">Nova Jogo</a>
            </p>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Data do Jogo
                        </th>
                        <th>
                            Equipa A
                        </th>
                        <th>
                            Equipa B
                        </th>
                        <th>
                            Equipa Vencedora
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.Games)
                    {
                        <tr>
                            <td>
                                @item.GameDate
                            </td>
                            <td>
                                @item.TeamA.TeamName
                            </td>
                            <td>
                                @item.TeamB.TeamName
                            </td>
                            <td>
                                @if (@item.TeamWinner != null)
                                {
                                    @item.TeamWinner.TeamName;
                                }
                            </td>
                            <td>
                                <a asp-controller="Games" asp-action="Stats" asp-route-id="@item.GameId" class="btn btn-primary">Estatisticas</a>
                                <a asp-controller="Games" asp-action="MapOfGame" asp-route-id="@item.GameId" class="btn btn-primary">Mapas</a>
                                <a asp-controller="Games" asp-action="Edit" asp-route-id="@item.GameId" class="btn btn-primary">Editar</a>
                                <a asp-controller="Games" asp-action="Delete" asp-route-id="@item.GameId" class="btn btn-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <a asp-controller="Events" asp-action="Index" class="btn btn-primary">Voltar a listagem de competições</a>
        </div>
    </div>
</div>

src/Client/Views/Games/MapOfGame.cshtml
@model Client.Models.MapOfGame
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    td, th {
        text-align: center;
    }
    table div {
        padding-left: 5vh;
        padding-right: 5vh;
    }
    a {
        padding-left: 2vh !important;
        padding-right: 2vh !important;
    }
    h4{
        margin: 0 !important;
    }
</style>
<hr />
<h4>Adicionar novo mapa jogado</h4>
<hr />
<form asp-action="AddMapOfGame" class="form-horizontal">
    <input type="hidden" value="@ViewBag.GameId" asp-for="GameId" />
    <table>
        <thead>
            <tr>
                <th>Mapa</th>
                <th>Resultado Equipa A</th>
                <th>Resultado Equipa B</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><select class="custom-select" asp-items="ViewBag.Maps" asp-for="MapaId"></select></td>
                <td><input asp-for="TeamAresult" class="form-control" /></td>
                <td><input asp-for="TeamBresult" class="form-control" /></td>
                <td><input type="submit" value="Adicionar Mapa" class="btn btn-success" /></td>
            </tr>
        </tbody>
    </table>
</form>
<hr />
<h4>Mapas Jogados</h4>
<hr />
<table>
    <thead>
        <tr>
            <th>
                    Mapa
            </th>
            <th>
                <div>
                    Resultado Equipa A
                </div>
            </th>
            <th>
                <div>
                    Resultado Equipa B
                </div>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (MapOfGame item in ViewBag.MapsOfGame)
        {
            <tr>
                <td>
                        @item.Mapa.Description
                </td>
                <td>
                    <div>
                        @item.TeamAresult
                    </div>
                </td>
                <td>
                    <div>
                        @item.TeamBresult
                    </div>
                </td>
                <td>
                    <a class="btn btn-danger" href="/Games/RemoveMapOfGame/?id=@item.GameId&idMapOfGame=@item.MapOfGameId">Remover mapa jogado</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a style="margin-top:5vh" class="btn btn-info" asp-action="Index" asp-route-id="@ViewBag.EventId">Voltar para a listagem de jogos</a>

src/Client/Views/Games/Stats.cshtml
@model Client.Models.StatPlayerOnGame
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

    Game game = ViewBag.Game;
}
<style>
    div, input, td div {
        text-align: center;
    }

    h5 {
        font-size: 2vh;
        margin-left: 2vh;
    }

    hr {
        margin: 1vh;
    }
</style>

<div class="row">
    <div class="col-md-12">
        <table>
            <thead>
                <tr>
                    <th>
                        <h4>Jogador</h4>
                    </th>
                    <th>
                        <h4>Kills</h4>
                    </th>
                    <th>
                        <h4>Deaths</h4>
                    </th>
                    <th>
                        <h4>ADR</h4>
                    </th>
                    <th>
                        <h4>Rating</h4>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="5">
                        <hr />
                        <h5>Team A - @game.TeamA.TeamName</h5>
                        <hr />
                    </td>
                </tr>
                @foreach (StatPlayerOnGame item in game.StatPlayerOnGame)
                {
                    @if (item.TeamId == game.TeamAId)
                    {

                        <tr class="stat">
                            <input type="hidden" asp-for="StatPlayerOnGameId" value="@item.StatPlayerOnGameId" />
                            <input type="hidden" asp-for="GameId" value="@item.GameId" />
                            <input type="hidden" asp-for="TeamId" value="@item.TeamId" />
                            <input type="hidden" asp-for="PlayerId" value="@item.PlayerId" />
                            <td>
                                <div class="form-group">
                                    <input class="form-control" value="@item.Player.Nickname" disabled />
                                </div>
                            </td>
                            <td>
                                <div class="form-group">
                                    <input asp-for="Kills" class="form-control" value="@item.Kills" />
                                </div>
                            </td>
                            <td>
                                <div class="form-group">
                                    <input asp-for="Deaths" class="form-control" value="@item.Deaths" />
                                </div>
                            </td>
                            <td>
                                <div class="form-group">
                                    <input asp-for="Adr" class="form-control" value="@item.Adr" />
                                </div>
                            </td>
                            <td>
                                <div class="form-group">
                                    <input asp-for="Rating" class="form-control" value="@item.Rating" />
                                </div>
                            </td>
                        </tr>
                    }
                }
                <tr>
                    <td colspan="5">
                        <hr />
                        <h5>Team B - @game.TeamB.TeamName</h5>
                        <hr />
                    </td>
                </tr>

                @foreach (StatPlayerOnGame item in game.StatPlayerOnGame)
                {
                    @if (item.TeamId == game.TeamBId)
                    {
            <tr class="stat">
                <input type="hidden" asp-for="StatPlayerOnGameId" value="@item.StatPlayerOnGameId" />
                <input type="hidden" asp-for="GameId" value="@item.GameId" />
                <input type="hidden" asp-for="TeamId" value="@item.TeamId" />
                <input type="hidden" asp-for="PlayerId" value="@item.PlayerId" />
                <td>
                    <div class="form-group">
                        <input class="form-control" value="@item.Player.Nickname" disabled />
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        <input asp-for="Kills" class="form-control" value="@item.Kills" />
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        <input asp-for="Deaths" class="form-control" value="@item.Deaths" />
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        <input asp-for="Adr" class="form-control" value="@item.Adr" />
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        <input asp-for="Rating" class="form-control" value="@item.Rating" />
                    </div>
                </td>
            </tr>
                    }
                }
                <tr style="padding:5vh;">
                    <td colspan="2">
                        <button style="float:left;" type="submit" onclick="sub()" class="btn btn-primary">Salvar estatisticas</button>
                        <a style="float:left; margin-left:2vh !important;" href="/Games/Index/@game.EventId" class="btn btn-danger">Descartar alterações</a>
                    </td>

                </tr>
            </tbody>
        </table>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.js"></script>
<script>

    function sub() {

        $('.stat').each(function (index, element) {

            var id = parseInt($(element).find('input[name=StatPlayerOnGameId]').val());

            var stat = {
                id: id,
                stat: {
                    StatPlayerOnGameId: id,
                    GameId: parseInt($(element).find('input[name=GameId]').val()),
                    TeamId: parseInt($(element).find('input[name=TeamId]').val()),
                    PlayerId: parseInt($(element).find('input[name=PlayerId]').val()),
                    Kills: parseInt($(element).find('input[name=Kills]').val()),
                    Deaths: parseInt($(element).find('input[name=Deaths]').val()),
                    Adr: parseFloat($(element).find('input[name=Adr]').val()),
                    Rating: parseFloat($(element).find('input[name=Rating]').val())
                }    
            };

            var url = "/Games/EditStat/" + id;
            $.post(url, stat, function (data, status) {
                console.log(status);
            });
        });
        window.location.href = "/Games/Index/" +@game.EventId;
    }
</script>