src/Client/Models/Event.cs
using Client.DataAtributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Client.Models
{
    public partial class Event
    {
        public Event()
        {
            Games = new List<Game>();
        }

        public int EventId { get; set; }
        [Required(ErrorMessage = "Obrigatório")]
        public string EventName { get; set; }
        [Required(ErrorMessage = "Obrigatório")]
        
        public DateTime DateOfStart { get; set; }
        [Required(ErrorMessage = "Obrigatório")]
        [DateLessThan("DateOfStart")]
        public DateTime DateOfEnd { get; set; }

        public virtual List<Game> Games { get; set; }
        public virtual List<Team> Teams { get; set; }

    }
}

src/Client/Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Client.Models
{
    public partial class Team
    {
        public Team()
        {
            Players = new List<Player>();
        }

        public int TeamId { get; set; }
        [Required(ErrorMessage = "Obrigatório")]
        [MaxLength(30,ErrorMessage = "O nome da equipa deve ter no maximo 30 caracteres")]
        public string TeamName { get; set; }
        [Required(ErrorMessage = "Obrigatório")]
        public int TeamRanking { get; set; }
        [Required(ErrorMessage = "Obrigatório")]
        [MaxLength(30, ErrorMessage = "O nome da equipa deve ter no maximo 30 caracteres")]
        public string TeamNationality { get; set; }


        //Relationship
        public virtual List<Player> Players { get; set; }
    }
}

src/Client/Controllers/EventsController.cs
using Client.Models;
using Client.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class EventsController : Controller
    {
        //
        private EventsRepository contextEvents = null;
        private GamesRepository contextGames = null;
        private TeamsRepository contextTeams = null;

        public EventsController()
        {
            this.contextEvents = new EventsRepository();
            this.contextGames = new GamesRepository();
            this.contextTeams = new TeamsRepository();
        }

        /// <summary>
        /// Pagina inicial dos eventos
        /// </summary>
        /// <returns>Retorna view</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Index()
        {
            try
            {
                var aux = await contextEvents.GetAllEvents();
                return aux == null ? RedirectToAction("Index", "Home") : View(aux);
            }
            catch (Exception e)
            {

                return View("Error", new Error { Title = "Listagem de competições", Message = e.Message });
            }

        }


        /// <summary>
        /// Pagina das equipas do evento
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <returns>Retorna a view</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Teams(int? id)
        {
            Event ev = null;
            IEnumerable<Team> tms = null;

            try
            {
                ev = await contextEvents.GetEventById(id);
                tms = await contextTeams.GetAllTeams(HttpContext);
                ViewBag.Event = ev;
                ViewBag.Teams = tms.Where(m => !ev.Teams.Any(a => a.TeamId == m.TeamId)).ToList();
            }
            catch (Exception e)
            {
                View("Error", new Error() { Title = "Listagem de jogos", Message = e.Message });
            }

            if (ev == null || tms == null)
            {
                return NotFound();
            }
            //
            return View("~/Views/Events/Teams.cshtml");
        }


        /// <summary>
        /// Pagina de detalhes do evento
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <returns>Retorna a view</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Details(int? id)
        {
            Event ev = null;


            if (id == null)
            {
                return View(NotFound());
            }
            try
            {
                ev = await contextEvents.GetEventById(id);
                ev.Games = await contextGames.GetGameByEventId(id);
            }
            catch (Exception e)
            {
                View("Error", new Error() { Title = "Listagem da competição", Message = e.Message });
            }

            if (ev == null || ev.Games == null)
            {
                return View(NotFound());
            }

            return View(ev);
        }


        /// <summary>
        /// Adiciona nova equipa ao evento
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <param name="TeamId">id da equipa</param>
        /// <returns>Retorna a view das equipas</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> AddTeam([Bind("id,TeamId")] int? id, int? TeamId)
        {
            Event ev = null;
            Team tm = null;


            if (id == null && TeamId == null)
            {
                return RedirectToAction("Teams");
            }
            try
            {
                ev = await contextEvents.GetEventById(id);
                tm = await contextTeams.GetTeamById(TeamId);
                if (ev != null && tm != null)
                {
                    if (!await contextEvents.AddTeamToEvent(HttpContext, ev, tm))
                    {
                        return RedirectToAction("Teams", new { id = id });
                    }
                }
            }
            catch (Exception e)
            {
                View("Error", new Error() { Title = "Adicionar equipa a competição", Message = e.Message });
            }

            if (ev == null || ev.Games == null)
            {
                return View(NotFound());
            }
            return RedirectToAction("Teams", new { id = id });
        }


        /// <summary>
        /// Remove equipa do evento
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <param name="TeamId">id da equipa</param>
        /// <returns>Retorna a view das equipas</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> RemoveTeam(int? id, int? TeamId)
        {
            Event ev = null;
            Team tm = null;


            if (id == null || TeamId == null)
            {
                return RedirectToAction("Index");
            }
            try
            {
                ev = await contextEvents.GetEventById(id);
                tm = await contextTeams.GetTeamById(TeamId);
                if (ev != null && tm != null)
                {
                    if (!await contextEvents.RemoveTeamFromEvent(HttpContext, ev, tm))
                    {
                        return RedirectToAction("Teams", new { id = id });
                    }
                }
            }
            catch (Exception e)
            {
                View("Error", new Error() { Title = "Adicionar equipa a competição", Message = e.Message });
            }

            if (ev == null || ev.Games == null)
            {
                return View(NotFound());
            }
            return RedirectToAction("Teams", new { id = id });
        }


        /// <summary>
        /// Pagina de criar novo evento
        /// </summary>
        /// <returns>Retorna a view</returns>
        [Authorize(Roles = "Admin,User")]
        public IActionResult Create()
        {
            return View();
        }


        /// <summary>
        /// Cria novo evento
        /// </summary>
        /// <param name="event">objeto evento</param>
        /// <returns>Retorna a view</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Create([Bind("EventId,EventName,DateOfStart,DateOfEnd")] Event @event)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await contextEvents.AddNewEvent(HttpContext, @event);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception e)
            {
                View("Error", new Error() { Title = "Nova competição", Message = e.Message });
            }

            return View(@event);
        }


        /// <summary>
        /// Pagina que edita um evento
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <returns>Retorna a View</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Edit(int? id)
        {
            Event ev = null;
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                ev = await contextEvents.GetEventById(id);
            }
            catch (Exception e)
            {

                View("Error", new Error() { Title = "Alteração de dados", Message = e.Message });
            }

            if (ev == null)
            {
                return NotFound();
            }
            return View(ev);
        }


        /// <summary>
        /// Edita um evento
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <param name="event">objeto evento alterado</param>
        /// <returns>Retorna a View</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,EventName,DateOfStart,DateOfEnd")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var ev = await contextEvents.EditEvent(HttpContext, @event, id);

                    if (ev != null)
                    {
                        View("Details", ev);
                    }
                    else
                    {
                        View("Error", new Error() { Title = "Alteração de dados", Message = "Não foi possivel alterar os dados pretendidos" });
                    }
                }
                catch (Exception e)
                {
                    View("Error", new Error() { Title = "Alteração de dados", Message = e.Message });
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }


        /// <summary>
        /// Pagina para eliminar um evento
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <returns>Retorna a View</returns>
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var ev = await contextEvents.GetEventById(id);
                if (ev == null)
                {
                    return NotFound();
                }

                return View(ev);
            }
            catch (Exception e)
            {

src/Client/Views/Events/Create.cshtml
@model Client.Models.Event

@{
    ViewData["Title"] = "Create";
}

<h1>Nova competição</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Nome da Competição</label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Data de Inicio</label>
                <input asp-for="DateOfStart" class="form-control" />
                <span asp-validation-for="DateOfStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Data de Fim</label>
                <input asp-for="DateOfEnd" class="form-control" />
                <span asp-validation-for="DateOfEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar nova Competição" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-danger">Descartar Dados</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Client/Views/Events/Delete.cshtml
@model Client.Models.Event

@{
    ViewData["Title"] = "Eliminar Competição";
}

<h1>Eliminar Competição</h1>

<h3>Tem certeza que deseja eliminar esta competição?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nome da Competição
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            Data de Inicio
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfStart)
        </dd>
        <dt class = "col-sm-2">
            Data de Fim
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfEnd)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EventId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-info">Voltar para a listagem</a>
    </form>
</div>

src/Client/Views/Events/Details.cshtml
@model Client.Models.Event
@{
    ViewData["Title"] = "Detalhes da Competição";
}

<h1>Detalhes da Competição</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nome da Competição
        </dt>
        <dd class = "col-sm-10">
            @Model.EventName
        </dd>
        <dt class = "col-sm-2">
            Data de Inicio
        </dt>
        <dd class = "col-sm-10">
            @Model.DateOfStart
        </dd>
        <dt class = "col-sm-2">
            Data de Fim
        </dt>
        <dd class = "col-sm-10">
            @Model.DateOfEnd
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EventId" class="btn btn-primary">Editar</a>
    <a asp-action="Index" class="btn btn-info">Voltar para a listagem</a>
</div>

src/Client/Views/Events/Edit.cshtml
@model Client.Models.Event

@{
    ViewData["Title"] = "Editar Competição";
}

<h1>Editar Competição</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EventId" />
            <div class="form-group">
                <label class="control-label">Nome da Competição</label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Data de Inicio</label>
                <input asp-for="DateOfStart" class="form-control" />
                <span asp-validation-for="DateOfStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Data de Fim</label>
                <input asp-for="DateOfEnd" class="form-control" />
                <span asp-validation-for="DateOfEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Descartar alterações</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Client/Views/Events/Index.cshtml
@model IEnumerable<Client.Models.Event>

@{
    ViewData["Title"] = "Competições";
}

<h1>Competições</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Nova competição</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Nome
            </th>
            <th>
                Data de Inicio
            </th>
            <th>
                Data de Fim
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EventName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfEnd)
                </td>
                <td>
                    <a class="btn btn-primary" onclick="VerifyGames(@item.EventId)" style="color:white">Jogos</a>
                    <a class="btn btn-primary" onclick="VerifyTeams(@item.EventId)" style="color:white">Equipas</a>
                    <a asp-action="Edit" asp-route-id="@item.EventId" class="btn btn-primary">Editar</a>
                    <a asp-action="Delete" asp-route-id="@item.EventId" class="btn btn-danger">Eliminar</a>
                    <a asp-action="Details" asp-route-id="@item.EventId" class="btn btn-secondary">Detalhes</a>
                </td>
            </tr>
        }
    </tbody>
</table>

src/Client/Views/Events/Teams.cshtml
@model Client.Models.Team
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    int id = @ViewBag.Event.EventId;
}


<div class="container">
    <hr />
    <div class="row">
        <div class="col-md-4">
            <h5>Nome do Evento</h5>
            <p>@ViewBag.Event.EventName</p>
        </div>
        <div class="col-md-4">
            <h5>Data de Inicio</h5>
            <p>@ViewBag.Event.DateOfStart</p>
        </div>
        <div class="col-md-4">
            <h5>Data de Fim</h5>
            <p>@ViewBag.Event.DateOfEnd</p>
        </div>
        <hr />
    </div>
    <hr />
    <h1>Equipas da Competição</h1>
    <div class="row" style="margin-top:1vh">
        <div class="form-group col-md-8">
            <form asp-controller="Events" asp-action="AddTeam">
                <input type="hidden" asp-for="@id" />
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01">Equipas</label>
                    </div>
                    <select class="custom-select" id="inputGroupSelect01" asp-for="TeamId"
                            asp-items="@(new SelectList(@ViewBag.Teams,"TeamId","TeamName"))">
                    </select>
                    <input type="submit" value="Adicionar Equipa" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>
    <div class="row" style="margin-top:1vh">
        <div class="col-md-8">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Nome da Equipa
                        </th>
                        <th>
                            Ranking da Equipa
                        </th>
                        <th>
                            Nacionalidade
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Team item in ViewBag.Event.Teams)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TeamName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TeamRanking)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TeamNationality)
                            </td>
                            <td>
                                <a type="submit" class="btn btn-danger" href="/Events/RemoveTeam/?id=@id&TeamId=@item.TeamId">Remover</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <a asp-controller="Events" asp-action="Index" class="btn btn-primary">Voltar a listagem de competições</a>
        </div>
    </div>

</div>