src/Client/Controllers/MapsController.cs
using Client.Models;
using Client.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class MapsController : Controller
    {
        private readonly MapsRepository contextMaps;

        public MapsController()
        {
            contextMaps = new MapsRepository();
        }

        // GET: Maps
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Index()
        {
            var aux = await contextMaps.GetAllMaps(HttpContext);

            try
            {
                if (aux != null)
                    return View(aux);
                else
                    return View("Error", new Error() { Title = "Listagem de mapas", Message = "Não foi possivel apresentar os mapas pretendidos" });
            }
            catch (Exception)
            {

                throw;
            }

            
        }

        // GET: Maps/Details/5
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var map = await contextMaps.GetMapById(id);
                if (map == null)
                {
                    return NotFound();
                }

                return View(map);
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Detalhes do mapa", Message = e.Message });
            }
            
        }

        // GET: Maps/Create
        [Authorize(Roles = "Admin,User")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Maps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Create([Bind("MapId,Description")] Map map)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await contextMaps.AddNewMap(HttpContext, map);
                    return RedirectToAction(nameof(Index));
                }
                return View(map);
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Criar mapa", Message = e.Message });
            }
            
        }

        // GET: Maps/Edit/5
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var map = await contextMaps.GetMapById(id);
                if (map == null)
                {
                    return NotFound();
                }
                return View(map);
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Editar mapa", Message = e.Message });
            }
            
        }

        // POST: Maps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Edit(int id, [Bind("MapId,Description")] Map map)
        {
            if (map == null || id != map.MapId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await contextMaps.EditMap(HttpContext, map,id);
                }
                catch (Exception)
                {
                    if (!MapExists(map.MapId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(map);
        }

        // GET: Maps/Delete/5
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var map = await contextMaps.GetMapById(id);
                if (map == null)
                {
                    return NotFound();
                }

                return View(map);
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Eliminar mapa", Message = e.Message });
            }

            
        }

        // POST: Maps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var map = await contextMaps.GetMapById(id);
                await contextMaps.DeleteMap(HttpContext, id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Eliminar mapa", Message = e.Message });
            }
            
        }

        [Authorize(Roles = "Admin,User")]
        private bool MapExists(int id)
        {
            try
            {
                return contextMaps.GetMapById(id) != null;
            }
            catch (Exception)
            {
                return false;
            }
            
        }
    }
}

src/Client/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Client.Repository;
using Client.Models;
using Microsoft.AspNetCore.Authorization;

namespace Client.Controllers
{
    public class UsersController : Controller
    {
        private UsersRepository contextUsers;

        public UsersController()
        {
            contextUsers = new UsersRepository();
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            try
            {
                return View(await contextUsers.GetAllUsers(HttpContext));
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Listagem de utilizadores", Message = e.Message });
            }
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var user = await contextUsers.GetUserById(HttpContext, id);
                if (user == null)
                {
                    return NotFound();
                }

                return View(user);
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Detalhes do utilizador", Message = e.Message });
            }
        }

        // GET: Users/Create
        public async Task<IActionResult> Create()
        {
            try
            {
                List<SelectListItem> list = new List<SelectListItem>();

                foreach (var item in await contextUsers.GetAllRoles(HttpContext))
                    list.Add(new SelectListItem() { Value = item, Text = item, Selected = false });
                //
                list[0].Selected = true;
                ViewBag.Roles = new SelectList(list, "Value", "Text");
                //
                return View();
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Criar utilizador", Message = e.Message });
            }
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Username,Email,Password,Role")] User user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await contextUsers.AddNewUser(HttpContext, user);
                    return RedirectToAction(nameof(Index));
                }
                return View(user);
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Criar utilizador", Message = e.Message });
            }
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                ViewBag.User = await contextUsers.GetUserById(HttpContext, id);

                List<SelectListItem> list = new List<SelectListItem>();

                foreach (var item in await contextUsers.GetAllRoles(HttpContext))
                {
                    if (ViewBag.User.Role == item)
                        list.Add(new SelectListItem() { Value = item, Text = item, Selected = true });
                    else
                        list.Add(new SelectListItem() { Value = item, Text = item, Selected = false });
                }
                ViewBag.Roles = new SelectList(list, "Value", "Text");

                if (ViewBag.User == null)
                {
                    return NotFound();
                }
                return View();
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Editar utilizador", Message = e.Message });
            } 
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Username,Email,Password,Role")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await contextUsers.EditUser(HttpContext, user, id);
                }
                catch (Exception e)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var user = await contextUsers.GetUserById(HttpContext, id);
                if (user == null)
                {
                    return NotFound();
                }

                return View(user);
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Eliminar utilizador", Message = e.Message });
            }
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var user = await contextUsers.GetUserById(HttpContext, id);
                if (user != null)
                    await contextUsers.DeleteUser(HttpContext, id);
                //
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return View("Error", new Error() { Title = "Eliminar utilizador", Message = e.Message });
            }
        }

        private bool UserExists(int id)
        {
            try
            {
                return contextUsers.GetUserById(HttpContext, id) != null;
            }
            catch (Exception)
            {
                return false;
            }
        }
    }
}

src/Client/Views/Shared/Unauthorized.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Access Deny</h1>

<a asp-action="Index" asp-controller="Home">Go To Home</a>
<a asp-action="Login" asp-controller="Home">Go To Login</a>

src/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CS : GO</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" asp-action="Index" asp-controller="Events"><img src="~/img/logo.jpg" width="250vh" style="color:white" /></a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Events">Competições</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Teams">Equipas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Players">Jogadores</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Parametrização
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-controller="Events" asp-action="Index">Competições</a>
                <a class="dropdown-item" asp-controller="Maps" asp-action="Index">Mapas</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="Teams" asp-action="Index">Equipas</a>
                <a class="dropdown-item" asp-controller="Players" asp-action="Index">Jogadores</a>

                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
<div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-controller="Users" asp-action="Index">Utilizadores</a>}
            </div>
        </li>
}
                </ul>
                @if (!User.Identity.IsAuthenticated)
                {
    <a class="btn btn-primary my-2 my-sm-0" type="button" asp-controller="Home" asp-action="Login">Iniciar Sessão</a> }
else
{
<a class="btn btn-danger my-2 my-sm-0" type="button" asp-controller="Login" asp-action="Logout">Logout</a>}
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row">
                Trabalho realizado por: Nº 12314 -> Sérgio Filipe Ribeiro Santos
            </div>
            <div class="row">
                Cadeira : ISI - Integração de Sistemas de Informação
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>